In [2]:
import pandas as pd
from pathlib import Path
datos = pd.read_csv("movies.csv")
datos["MOVIES"]

0                             Blood Red Sky
1       Masters of the Universe: Revelation
2                          The Walking Dead
3                            Rick and Morty
4                           Army of Thieves
                       ...
9994                         The Imperfects
9995                                 Arcane
9996                      Heart of Invictus
9997                         The Imperfects
9998                         The Imperfects
Name: MOVIES, Length: 9999, dtype: str

Selecciona las columnas "MOVIES" y "YEAR" (como DataFrame).

In [3]:
datos[["MOVIES", "YEAR"]]

                                   MOVIES         YEAR
0                           Blood Red Sky       (2021)
1     Masters of the Universe: Revelation     (2021– )
2                        The Walking Dead  (2010–2022)
3                          Rick and Morty     (2013– )
4                         Army of Thieves       (2021)
...                                   ...          ...
9994                       The Imperfects     (2021– )
9995                               Arcane     (2021– )
9996                    Heart of Invictus     (2022– )
9997                       The Imperfects     (2021– )
9998                       The Imperfects     (2021– )

[9999 rows x 2 columns]

Saca las primeras 8 filas usando slicing estilo df[:8].

In [4]:
datos[:8]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN

Con .loc, selecciona las filas 0 a 4 (incluidas) y columnas "MOVIES" y "RATING".

In [5]:
datos.loc[0:4, ["MOVIES", "RATING"]]

                                MOVIES  RATING
0                        Blood Red Sky     6.1
1  Masters of the Universe: Revelation     5.0
2                     The Walking Dead     8.2
3                       Rick and Morty     9.2
4                      Army of Thieves     NaN

Con .loc, selecciona las filas 20 a 30 (incluidas) y columnas "YEAR", "GENRE", "VOTES".

In [6]:
datos.loc[20:30, ["YEAR", "GENRE", "VOTES"]]

           YEAR                                       GENRE    VOTES
20       (2021)        \nDrama, Horror, Mystery               36,634
21  (1994–2004)               \nComedy, Romance              880,918
22     (2014– )      \nAction, Adventure, Drama              320,264
23     (2013– )                  \nCrime, Drama              393,414
24     (2021– )  \nAnimation, Action, Adventure                  NaN
25       (2021)       \nDrama, History, Romance                4,681
26  (2013–2020)      \nAction, Adventure, Drama              459,913
27     (2015– )                  \nCrime, Drama              347,857
28  (2005–2020)        \nDrama, Fantasy, Horror              404,273
29     (2013– )         \nCrime, Drama, Mystery              213,522
30       (2021)               \nHorror, Mystery               27,447

Con .iloc, selecciona filas 0 a 4 y las primeras 3 columnas (por posición).

In [7]:
datos.iloc[0:5, 0:3]

,MOVIES,YEAR,GENRE
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller"
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure"
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller"
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy"
4,Army of Thieves,(2021),"\nAction, Crime, Horror"

In [9]:
datos[["MOVIES"]]

                                   MOVIES
0                           Blood Red Sky
1     Masters of the Universe: Revelation
2                        The Walking Dead
3                          Rick and Morty
4                         Army of Thieves
...                                   ...
9994                       The Imperfects
9995                               Arcane
9996                    Heart of Invictus
9997                       The Imperfects
9998                       The Imperfects

[9999 rows x 1 columns]